module Rex
module Post
module Meterpreter
module Extensions
module Lua

TLV_TYPE_LUA_RUN_SCRIPT							= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 2)
TLV_TYPE_LUA_LIST_TOKENS_IMPERSONATION        	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 3)
#TLV_TYPE_LUA_LIST_TOKENS_ORDER       	= TLV_META_TYPE_UINT| (TLV_EXTENSIONS + 4)
#TLV_TYPE_LUA_IMPERSONATE_TOKEN    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 5)
#TLV_TYPE_LUA_GENERIC_RESPONSE    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 6)

end
end
end
end
end
